/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistoryByYear.java
 */
package hotel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author shreee
 */
public class HistoryByYear extends javax.swing.JPanel implements ActionListener{

    DefaultTableModel dm;
    TableProperties props;
    /** Creates new form HistoryByYear */
    public HistoryByYear() {
        dm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //Only the third column
                return false;
            }
        };
        initComponents();
        props = new TableProperties(tblHistory, dm);
        String[] cols = {"Res. ID", "Guest ID", "Guest Name", "Rooms", "No. of Guests", "Check in", "Check out", "Total paid"};
        props.addColumns(cols);
        props.changeColumnProperties(new int[]{80, 80, 80, 80, 80, 110, 110, 100});
        createPopup();
        btnView.addActionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        yearpicker = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();

        btnView.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnView.setText("View");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel2.setText("Select year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(yearpicker, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(btnView)
                .addComponent(yearpicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnView, jLabel2, yearpicker});

        tblHistory.setModel(dm);
        tblHistory.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistory;
    private com.toedter.calendar.JYearChooser yearpicker;
    // End of variables declaration//GEN-END:variables
    
    private void createPopup(){
    JPopupMenu popup = new JPopupMenu();
        JMenuItem myMenuItem1 = new JMenuItem("View Full Details");
        JMenuItem myMenuItem2 = new JMenuItem("Do Nothing");
        myMenuItem1.addActionListener(this);
        myMenuItem2.addActionListener(this);
        popup.add(myMenuItem1);
        popup.add(myMenuItem2);
        MouseListener popupListener = new PopupListener(popup,tblHistory);
        tblHistory.addMouseListener(popupListener);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("View Full Details"))
        {
//            FullDetails fd = new FullDetails("Complete Details");
//            fd.displayDetails((Integer)dm.getValueAt(tblHistory.getSelectedRow(),0));
            Report r1 = new Report();
            r1.displayCheckoutReport((Integer)dm.getValueAt(tblHistory.getSelectedRow(), 0));
        }else if (e.getSource()== btnView)
        {
            int yr = yearpicker.getYear();
            viewDetails(yr);
        }
    }
    
    private void viewDetails(int yr) {
        dm.setRowCount(0);
       Connection conn = DbConnection.getConnection();
        try {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery("select * from reservation_history,guest where guest.id = reservation_history.guest_id order by reservation_history.reservation_id");
            while (rs.next()) {
                Date checkin = rs.getDate("check_in");
                Calendar cal = Calendar.getInstance();
                cal.setTime(checkin);
                int chkin_yr = cal.get(Calendar.YEAR);
                if (chkin_yr == yr) {
                    dm.addRow(new Object[]{rs.getInt("reservation_id"),rs.getInt("guest_id"),rs.getString("f_name")+" "+ rs.getString("l_name"),rs.getString("rooms"),
                    rs.getInt("num_of_guests"),rs.getDate("check_in"),rs.getDate("check_out"),rs.getInt("total_paid")});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(HistoryAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
