/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PasswordControl.java
 *
 * 
 */
package hotel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author shreee
 */
public class PasswordControl extends javax.swing.JPanel implements ActionListener,KeyListener{

    /** Creates new form PasswordControl */
    public PasswordControl() {
        initComponents();
        btnChange.addActionListener(this);
        txtNewPassword.addKeyListener(this);
        txtConfirmPassword.addKeyListener(this);
        btnChange.setEnabled(false);
        setBorder(BorderFactory.createTitledBorder(null, "Password Control",TitledBorder.CENTER,TitledBorder.ABOVE_TOP));
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox();
        txtOldPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();

        setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel2.setText("Select User");

        cmbUser.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmbUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Staff" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel4.setText("Old Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel3.setText("New Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel5.setText("Confirm Password");

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password should be at least 6 characters long");

        btnChange.setFont(new java.awt.Font("Tahoma", 0, 14));
        btnChange.setText("Change");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnChange)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConfirmPassword)
                            .addComponent(txtNewPassword)
                            .addComponent(txtOldPassword)
                            .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChange)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JComboBox cmbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnChange) {
            if (cmbUser.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "please select user first ");
                return;
            }
            if (txtOldPassword.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "please enter old password first");
                return;
            }
            if (passwordMatched())
            {
                changePassword();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Old Password doesnot match");
            }
        } 
    }
    
    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        comparePasswords();
    }

    private void comparePasswords() {
        String p1 = new String(txtNewPassword.getPassword());
        String p2 = new String(txtConfirmPassword.getPassword());
        if (p1.equals(p2)) {
            if (p1.length() >= 6 ) {
                btnChange.setEnabled(true);
            }
        } else {
            btnChange.setEnabled(false);
        }
    }
    
    private boolean passwordMatched() {
        Connection conn = DbConnection.getConnection();
        try
        {
            PreparedStatement stat = conn.prepareStatement("select count(*) from users where username=? and password=?");
            stat.setString(1, (String)cmbUser.getSelectedItem());
            stat.setString(2, new String(txtOldPassword.getPassword()));
            ResultSet rs = stat.executeQuery();
            rs.next();
            int c = rs.getInt(1);
            if (c ==1)
            {
                return true;
            }
        }catch(Exception e){}
        return false;
    }

    private void changePassword() {
        Connection conn = DbConnection.getConnection();
        try
        {
            PreparedStatement stat = conn.prepareStatement("update users set password=? where username=?");
            stat.setString(2, (String)cmbUser.getSelectedItem());
            stat.setString(1, new String(txtConfirmPassword.getPassword()));
            int c = stat.executeUpdate();
            if (c >= 1)
            {
                JOptionPane.showMessageDialog(null, "Password Successfully changed");
                MyLogger.writeLog("Password changed", " new password ");
                txtOldPassword.setText("");
                txtNewPassword.setText("");
                txtConfirmPassword.setText("");
            }
        }catch(Exception e){}
    }
}
